// <auto-generated />
using System;
using InventorySystem.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySystem.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20230329103751_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("InventorySystem.Entities.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemPar")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = new Guid("6a41daee-22ef-47a1-b269-40ef111afe79"),
                            ItemAmount = 6,
                            ItemName = "Hay",
                            ItemPar = 10
                        },
                        new
                        {
                            ItemId = new Guid("b31ac87e-0a50-41c0-910e-f305ebfcca88"),
                            ItemAmount = 25,
                            ItemName = "Diesel Fuel",
                            ItemPar = 10
                        },
                        new
                        {
                            ItemId = new Guid("4bb37e1b-aeab-4dc0-970e-87b30efb6093"),
                            ItemAmount = 12,
                            ItemName = "Unleaded Fuel",
                            ItemPar = 10
                        });
                });

            modelBuilder.Entity("InventorySystem.Entities.Livestock", b =>
                {
                    b.Property<Guid>("LivestockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockBreed")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockDob")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockDos")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivestockType")
                        .HasColumnType("TEXT");

                    b.HasKey("LivestockId");

                    b.ToTable("Livestocks");

                    b.HasData(
                        new
                        {
                            LivestockId = new Guid("786e921d-8aae-4f82-9270-5251a6f1c685"),
                            LivestockBreed = "Black Angus",
                            LivestockComments = "Rambo is used to help rear new calves.",
                            LivestockDob = "Unknown",
                            LivestockDos = "n/a",
                            LivestockName = "Rambo",
                            LivestockType = "Mentor Animal"
                        },
                        new
                        {
                            LivestockId = new Guid("b46263f4-c750-459c-95c2-7ae362e15382"),
                            LivestockBreed = "Black Angus",
                            LivestockDob = "2019",
                            LivestockDos = "TBD",
                            LivestockName = "Gimpy",
                            LivestockType = "Meat Steer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
